// <auto-generated />
namespace CommunityMedicine.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class identitymodeladded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identitymodeladded));
        
        string IMigrationMetadata.Id
        {
            get { return "201912161129152_identity-model-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
