//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Medicine_Automation_App.Reports.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CommunityMedicineDBEntities : DbContext
    {
        public CommunityMedicineDBEntities()
            : base("name=CommunityMedicineDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<ReportMedicineStore_Result> ReportMedicineStore()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReportMedicineStore_Result>("ReportMedicineStore");
        }
    
        public virtual ObjectResult<ReportPatientTreatments_Result> ReportPatientTreatments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReportPatientTreatments_Result>("ReportPatientTreatments");
        }
    }
}
